# Generated by Django 5.0 on 2025-09-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='can_create_items',
            field=models.BooleanField(default=False, help_text='Permite al rol crear nuevos items.'),
        ),
        migrations.AddField(
            model_name='rol',
            name='can_delete_items',
            field=models.BooleanField(default=False, help_text='Permite al rol eliminar items.'),
        ),
        migrations.AddField(
            model_name='rol',
            name='can_update_items',
            field=models.BooleanField(default=False, help_text='Permite al rol editar items existentes.'),
        ),
    ]
