# Generated by Django 5.0 on 2025-09-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="username",
        ),
    ]
